// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sapawarga/video-service/repository (interfaces: DatabaseI)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	model "github.com/sapawarga/video-service/model"
	reflect "reflect"
)

// MockDatabaseI is a mock of DatabaseI interface
type MockDatabaseI struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseIMockRecorder
}

// MockDatabaseIMockRecorder is the mock recorder for MockDatabaseI
type MockDatabaseIMockRecorder struct {
	mock *MockDatabaseI
}

// NewMockDatabaseI creates a new mock instance
func NewMockDatabaseI(ctrl *gomock.Controller) *MockDatabaseI {
	mock := &MockDatabaseI{ctrl: ctrl}
	mock.recorder = &MockDatabaseIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDatabaseI) EXPECT() *MockDatabaseIMockRecorder {
	return m.recorder
}

// GetListVideo mocks base method
func (m *MockDatabaseI) GetListVideo(arg0 context.Context, arg1 *model.GetListVideoRepoRequest) ([]*model.VideoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListVideo", arg0, arg1)
	ret0, _ := ret[0].([]*model.VideoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListVideo indicates an expected call of GetListVideo
func (mr *MockDatabaseIMockRecorder) GetListVideo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListVideo", reflect.TypeOf((*MockDatabaseI)(nil).GetListVideo), arg0, arg1)
}

// GetMetadataVideo mocks base method
func (m *MockDatabaseI) GetMetadataVideo(arg0 context.Context, arg1 *model.GetListVideoRepoRequest) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataVideo", arg0, arg1)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadataVideo indicates an expected call of GetMetadataVideo
func (mr *MockDatabaseIMockRecorder) GetMetadataVideo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataVideo", reflect.TypeOf((*MockDatabaseI)(nil).GetMetadataVideo), arg0, arg1)
}
