name: Go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Setting Env
      run: cp ./config.example.json ./config.json
    - name: Build
      run: make build
    - name: Test
      run: go test ./... -coverprofile=./coverage.out
    - name: Test coverage
      run: go tool cover -html=./coverage.out